apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vikunja

helmCharts:
- name: vikunja
  repo: https://k8s-at-home.com/charts/
  version: 5.1.0
  releaseName: vikunja
  namespace: vikunja
  valuesFile: values.yaml

resources:
- namespace.yaml