apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - components/deployment.yaml
  - components/service.yaml
  - components/ingress.yaml

commonLabels:
  app: static-server