apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plane

generators:
  - ksops-generator.yaml

helmCharts:
  - name: plane-ce
    repo: https://helm.plane.so/
    version: 1.4.0
    releaseName: plane
    namespace: plane
    valuesFile: values.yaml