planeVersion: v1.1.0

dockerRegistry:
  enabled: false
  host: "index.docker.io/v1/"
  loginid: ""
  password: ""

redis:
  local_setup: true
  image: valkey/valkey:7.2.11-alpine
  servicePort: 6379
  storageClass: ""
  volumeSize: 100Mi
  pullPolicy: IfNotPresent
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

postgres:
  local_setup: true
  image: postgres:15.7-alpine
  servicePort: 5432
  storageClass: ""
  volumeSize: 1Gi
  pullPolicy: IfNotPresent
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

rabbitmq:
  local_setup: true
  image: rabbitmq:3.13.6-management-alpine
  pullPolicy: IfNotPresent
  servicePort: 5672
  managementPort: 15672
  storageClass: ""
  volumeSize: 100Mi
  default_user: plane
  default_password: plane
  external_rabbitmq_url: ''
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

minio:
  local_setup: false
  
web:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-frontend
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

space:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-space
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

admin:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-admin
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

live:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-live
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

api:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

beatworker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

external_secrets:
  rabbitmq_existingSecret: ''
  pgdb_existingSecret: ''
  doc_store_existingSecret: 'plane-docstore-cred'
  app_env_existingSecret: 'plane-app-env'
  live_env_existingSecret: ''

env:
  pgdb_username: plane
  pgdb_password: plane
  pgdb_name: plane

  docstore_bucket: "uploads"
  doc_upload_size_limit: "5242880" # 5MB

  aws_access_key: ""
  aws_secret_access_key: ""
  aws_region: "us-east-1"
  aws_s3_endpoint_url: "https://s3.yadon3141.com"

  secret_key: ""
  live_server_secret_key: ""

  sentry_dsn: ""
  sentry_environment: ""

  cors_allowed_origins: ""
  default_cluster_domain: cluster.local

  api_key_rate_limit: "60/minute"
