planeVersion: v1.1.0

dockerRegistry:
  enabled: false
  host: "index.docker.io/v1/"
  loginid: ""
  password: ""

ingress:
  enabled: true
  appHost: "plane.yadon3141.com"
  ingressClass: "traefik"
  ingress_annotations: { "nginx.ingress.kubernetes.io/proxy-body-size": "5m" }

ssl:
  tls_secret_name: "" # If you have a custom TLS secret name
  createIssuer: false
  issuer: "http" # Allowed : cloudflare, digitalocean, http
  token: "" # not required for http
  server: https://acme-v02.api.letsencrypt.org/directory
  email: plane@example.com
  generateCerts: false

redis:
  local_setup: true
  image: valkey/valkey:7.2.11-alpine
  servicePort: 6379
  storageClass: ""
  volumeSize: 100Mi
  pullPolicy: IfNotPresent
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

postgres:
  local_setup: true
  image: postgres:15.7-alpine
  servicePort: 5432
  storageClass: ""
  volumeSize: 1Gi
  pullPolicy: IfNotPresent
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

rabbitmq:
  local_setup: true
  image: rabbitmq:3.13.6-management-alpine
  pullPolicy: IfNotPresent
  servicePort: 5672
  managementPort: 15672
  storageClass: ""
  volumeSize: 100Mi
  default_user: plane
  default_password: plane
  external_rabbitmq_url: ''
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

minio:
  image: minio/minio:latest
  image_mc: minio/mc:latest
  local_setup: false
  pullPolicy: IfNotPresent
  root_password: password
  root_user: admin
  storageClass: ""
  volumeSize: 1Gi
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
    minio_endpoint_ssl: false

web:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-frontend
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

space:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-space
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

admin:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-admin
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

live:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-live
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

api:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

beatworker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

external_secrets:
  rabbitmq_existingSecret: ''
  pgdb_existingSecret: ''
  doc_store_existingSecret: 'plane-docstore-cred'
  app_env_existingSecret: ''
  live_env_existingSecret: ''

env:
  remote_redis_url: "" #INCASE OF REMOTE REDIS ONLY

  # POSTGRES DB VALUES
  pgdb_username: plane
  pgdb_password: plane
  pgdb_name: plane
  pgdb_remote_url: "" #INCASE OF REMOTE PG DB URL ONLY

  docstore_bucket: "uploads"
  doc_upload_size_limit: "5242880" # 5MB

  aws_region: "us-east-1"
  aws_s3_endpoint_url: "https://s3.yadon3141.com"

  secret_key: "60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5"
  live_server_secret_key: "htbqvBJAgpm9bzvf3r4urJer0ENReatceh"

  sentry_dsn: ""
  sentry_environment: ""

  cors_allowed_origins: ""
  default_cluster_domain: cluster.local

  api_key_rate_limit: "60/minute"

