apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announce-home
spec:
  serviceSelector:
    matchLabels:
      expose: "lb"           
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
    - ^eth[0-9]+$
    - ^en[a-z0-9]+$
  loadBalancerIPs: true
  externalIPs: false         
