apiVersion: v1
kind: Secret
metadata:
    name: minio-static-server
    namespace: default
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:nTT+411hDEqI4zHzDYSw8By9VKzuetLCerc9/94p/o5jRw==,iv:+EAmgR6UjTDSfuDAy7j3cKOxBYKxF/s8bwuT9c68Va0=,tag:pTNFMilfdaV8TB960DneBQ==,type:str]
    access-key: ENC[AES256_GCM,data:xhKbyz/VRHIS4WQkN7ZGB5RFiW0=,iv:xJdpMMVow3nU5ngnIOLmwVFaZxw7Ues/fI+KwWb+vZw=,tag:dW0kUGuIG/vPK09CE/g3kQ==,type:str]
    secret-key: ENC[AES256_GCM,data:Q0TIM6CDUcocwWFanTNSm60EPnlgTkP3v350A/cQvOUFYCNOcLog6Q==,iv:WSzPgg+s0T5RGw90cq00vgOrSq5GrP6+90YWYxdiXu4=,tag:ATJrTqokP+JeNdduZ8wc4w==,type:str]
    use-ssl: ENC[AES256_GCM,data:+7j44Vo=,iv:YPFYiFLU/dQb1JGUFUu0hYy9eLLYbrsIjqZemySvxfQ=,tag:sIKcSBKx/6cutz2+nBTszw==,type:str]
sops:
    age:
        - recipient: age1k7d7drqkwqawwfxhxzz6gd5ur7ns68xd5kpn69x8t6yvf9cp3pmsuukrgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QVlNM052MlNpZlNyOFpj
            SkFzbndOTzNFNDNOYWZ0ZTE0ZmRGMnZjOXlNCnl2ZEVRMUp3ekNzdERZWW80MUw2
            UllzQ2FFcG8rMUZxNGJiZVZTRExieGsKLS0tIDFLMnk4bGU2TXJGeUQvUm1FS0lu
            aGs5UHVxeUQxalk5SDFLdE84dW9taG8K6HVLuMskbxTmyxadaC2rP0PXYABODsZ9
            7K218XwFVeedmsOY8bvdWbtcxo4htOB1uZ223GzAyvN1gjzE6ZZiQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T19:25:22Z"
    mac: ENC[AES256_GCM,data:0Ctlx7UB21/2yIZU1L+sbftfp4byFQMK5ZWxddj3MuVSXkcdBEx6BHVTETxnqKVxGpn9gW7IXc+Iz9PaAqWHEpHq9lgm6jrvpdgTsN+pJlWT4Q48d1eUwGB7bXC6l2IYc2eShdPBqpBML+1xCtbfPC3AT5sQGwFeHw/aKPOx3R0=,iv:wq/U4tR2N8N0ujMsbz7oLZH8x/iIKUlA6+uW2GxZhRw=,tag:W2uvGUIh26Y6mENS1ocE/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
