apiVersion: v1
kind: Secret
metadata:
    name: minio-static-server
    namespace: default
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:ZzwhZKcqo+YMVdoR7IZJuB+t432pXNSUyIvbNkU=,iv:s31uTViEO745XZOkrHorXvwZUN7zvvazbJ71xcZ0HqI=,tag:bZc6pTns4tYAJYS56Cuuvg==,type:str]
    access-key: ENC[AES256_GCM,data:Omx5+Cp1DJ6JnqJKha7NiNUlfb0=,iv:gpa3WNSxshslprozG+RAI8vLfYRFJ+n/duJS8hqPQIk=,tag:lj2/Wbh5U3K0L2rQQOlkCw==,type:str]
    secret-key: ENC[AES256_GCM,data:JtEZEWsyN3sX7gSVEMXyNz07OaSEywVVjN7Hvycuj5hC8IwueGURrg==,iv:l9jIypNmS7Aeniy4AKs6OCoC4EbPnX/26xk9uBDudFY=,tag:7b+9PCPSLMJytk/LuOajZw==,type:str]
    use-ssl: ENC[AES256_GCM,data:Dqou0fE=,iv:fvEdUman+ZEoBmkDEnOWRpikS+pzLBCJcNZOli8IdFE=,tag:iHReajZepjm28i1+VNTBhA==,type:str]
sops:
    age:
        - recipient: age1k7d7drqkwqawwfxhxzz6gd5ur7ns68xd5kpn69x8t6yvf9cp3pmsuukrgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYWQ5UVM5MDM0bGo0NlMr
            dWlpZUwyVGR2MzEzQXJ3cE9qL2ZheHhlQ21zCnVhUEtLeThLYUtvSjhPaWo4ZmU0
            UkJVcDNqcjhBc3h2bVo3Y2U5VU13QXcKLS0tIGVQeTcrakp5bVY5WVo1ZUtZcnlt
            ajhkNU5uWFhTc1R6SXoyS2V1d3NyaVEKfyBBDZ8JQR73/gRqOKlj2uiL+l0BtzCM
            UDu1mVdqKJmuUrnuTnwWXMqh/RF9FVkpbl1O5wxfLfqka6b2xWxiSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T17:55:07Z"
    mac: ENC[AES256_GCM,data:fFeWk2btAmLUaQjkTCaxZrn42JsrEWv0bsgorUy5rDj9g8NevneX0Ivzoq5Guck4SaCaRnlVvMzsdlkIYvEkuaYUwOZ/xrbPy0Sh7zpk3xuxBqGdqAEGL8WmUC78qqidGh0NuPk0aKu5qOeQcZo7KnvX68J2C4M1otA4XHg4p9Y=,iv:sUZ8C7buPpqVL7yE20IgTZJeEEo0Y3Uw1IFqKY0DxEs=,tag:ZQ62OBeCuF3L3TdP80D6Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
