apiVersion: v1
kind: Secret
metadata:
    name: password
    namespace: harbor
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:jSDWmlhYOGP1Q/E0QxEw4gXvnZ7/L+i9lqt8zzUU9kZf6hjnRGzwDOGKgsQ=,iv:+gbddTvo9laSQpztv3guUG5rc1mlcx8wwvzpTz816bs=,tag:2wOq/SoL9ANS4wVq0wJQmw==,type:str]
sops:
    age:
        - recipient: age1k7d7drqkwqawwfxhxzz6gd5ur7ns68xd5kpn69x8t6yvf9cp3pmsuukrgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQVAxcmJDMU1zWGROMWx4
            ZXluczIvd1RsbGIyV29iZ0MwNXRhamYvR2lzCm9CSmh1ZGd3Q2VKRUN1ckppOWZ0
            NUJ0RmozUFM2YkJYMDRYTDk4amhyYU0KLS0tIHBQTXZjb3VBOVIvOFVZeDFkMVdz
            akVOMEo3VndYQUtPZTNmMElXTmlWdk0KrHTEtqKjssXuEGtf6LtyIad7h/ere2CF
            LQaEhxHh48WruJL21C8YRIgpSl3V+ohPA0aAd43C2+N5nyrQi8WGlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T17:04:31Z"
    mac: ENC[AES256_GCM,data:xgsMrNIU1SRkkiiXqyhN0K5hqW6d+97XUvjJR0btSo9vVTCNFzi5EiWkAc/wEI6+ZK+umHiS4zKHTb+7D9I/zsQ8XMgJrOT6D72pJhBotJT5yNd1YnZOJpYjbOi9Wth+GcZuZWmaG7L/re6r2R2+1ECffTu21AiIW4lNLGRxe+8=,iv:F7d0v+xNSSRMVa5akLILQceIbQ9+shjjUz1YfpDICmY=,tag:FexBExuYm0iMyP3GAEfSCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
