apiVersion: v1
kind: Secret
metadata:
    name: secret-key
    namespace: harbor
type: Opaque
stringData:
    secretKey: ENC[AES256_GCM,data:bQavTt1Paz239eTOJ+FxE41JyCERAjKi,iv:BcGgGHSfxYNljlPLqBuJO272J2vkLaGWmc8HZ0QnVYY=,tag:RB5WmdH0QiFbr6ZR0A1QuQ==,type:str]
sops:
    age:
        - recipient: age1k7d7drqkwqawwfxhxzz6gd5ur7ns68xd5kpn69x8t6yvf9cp3pmsuukrgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYzc3c2lDVEpEU2lQaENv
            V3FJUld0cVVlN3hIQXhQdjZZYVI2SkFoaEhBCmpSUHg3V0pBVXNXLzlETGFSc1Er
            TFkyMVhidU5PbnY5amhkbVdlY2hSYmsKLS0tIHZMYzE0R05BQm9IL0JIdCtCOU5m
            WnRTdE5GdHdkUE8vOUZ6OVFpUjlremsKKIqg3aH9RBh1OqCW0wHjCmslZmwjviag
            0p3afHE+8hJmfqPnq95SuRikO4C9RHs9rWikGwJX6bCvOrW4gTNi0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T17:05:09Z"
    mac: ENC[AES256_GCM,data:C3oLKx1OZEhcZhSVkqoTkHFDjQLLeT1KGWVF9A8Nvrz2rcH/i3aJbJ6K3AQVGQs2y41Sc8nVA8DnnXpRf/V5I4Zf02CL/+XLFlwd+4mje+RFtfPWZKIzznYnbX2FGJsQTxIAJCBefV2KU3ozYQeWw7ZXZCt2zRGslCPvsXRnedE=,iv:93vSNQ/2oTuO7vdmlAsEx+a+145hGkmaVV5u58V2hFg=,tag:B06jK7LOskw4t5cLJKEmvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
