apiVersion: v1
kind: Secret
metadata:
  name: storage
  namespace: harbor
type: Opaque
stringData:
  REGISTRY_STORAGE_S3_ACCESSKEY: "your-s3-access-key"
  REGISTRY_STORAGE_S3_SECRETKEY: "your-s3-secret-key"