apiVersion: v1
kind: Secret
metadata:
    name: storage
    namespace: harbor
type: Opaque
stringData:
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:MPY3YPN8QDshXe/tb9M88JT3Cw8=,iv:DydZdRhLdkhX2QRAAGwRki5Lho6CBKNmR3bDkSR+RoM=,tag:S01B6ZqaR1M9CsibvXQr0A==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:gpc1HaFbD2HqQ32DX1Z/dcTJ1H/VuS31grh80ejYky/2Z70APS+iaA==,iv:l27hG3e/MS7P36r3hORru1K8Gl3mscaK2+qD2NyuH9M=,tag:FOsWPrbwZsFI647ZWlTCgQ==,type:str]
sops:
    age:
        - recipient: age1k7d7drqkwqawwfxhxzz6gd5ur7ns68xd5kpn69x8t6yvf9cp3pmsuukrgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQkpGZFRjSmIrVDdwblFq
            NmVsL0JXaE43NSt6SFMzWDFGOVI3UlV3L1FFCjlGNURIY1ZnMWY1VmJTQnAzMUVF
            Zy95aFY2dkhFVFM0Y2V0cFR1N2VxZ2sKLS0tIDdIZWJxeXhCQ09qNW5zKzRvRlRO
            ZHVEMkU3V2Vwamt3eUhOSEhyU2dUS2sKOji9ZqLEgas9zyVXyK11800a0Z6JBO0R
            dcd2QJgGmw4AeTfiPF7MlC9PNV42C74Yor36GaeqrprkPlMewSb6ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T17:07:05Z"
    mac: ENC[AES256_GCM,data:c0EqfNDbp71t3oc1DkC5MN1Wu3pq6QTUFEST4ysTkTudp2Uvv20YTcE+Fe8OrpCR4V4Y5rHgA4VoJVuXTctF4SlzA5a+2maAumYOm4ZuAWHYVpiPB4XthRDB8LpK3Vi6Mu2Q8w26MELmyKPZnjNeTL2/Hy8hTNtFrVfgbvHr9+k=,iv:IoV2nyXhtqYWPjrkhsnw2rhKAZY6o9h3kma+CBOQ0UM=,tag:FkIFefVkFb1rfiejSDN2mA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
