apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ingress.yaml
  - repo-server-patch.yaml
  - ../base-argocd

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - kustomize.buildOptions=--enable-alpha-plugins --enable-exec

patchesStrategicMerge:
  - repo-server-patch.yaml
