resources:
  - ingress.yaml
  - repo-server-pahch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - kustomize.buildOptions=--enable-alpha-plugins --enable-exec