apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:bdeFfpDbHdgHOOaa2/qlkthYnjweHpSzs0qRWhj4ushMpv++db/EXoYd3mENlctckBN9qkiYvYjKHXFBwqvwzThapg8rzyCSYesk5JyqsIqTH6WlhNrYlizFZS4XNanRmSV5AF8UZW3ZJnJEKAu58mphWsOrhjkyNyr5CFehm4JOD5/us4PsV20rnecVFo1rbCDrTGDncnBwZU0YY1y1gPEUtpacrl8plszcoDlp+wbZyNweCBBGIVj3lfWIs1OjfSXB7u4bWD+3DK2Q2HLNK9/N0QSklLOi,iv:L9wMzjQPVIDmesRHloRqG0qaY0/68Xzq/OryOJbVOsg=,tag:GQcywaWUgxFOwAON1NZ8pA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - recipient: age1k7d7drqkwqawwfxhxzz6gd5ur7ns68xd5kpn69x8t6yvf9cp3pmsuukrgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NTRqK1BYd0cxSUV6SWc3
            MzEzcnlJL1FNZ3BwVys3bGdqdllHcXp0SFFNCmtpNzBhSjEyK1oyKzl0VlU3R0Rm
            c3QvdzBGVXVvQ2lSdmI4ZVhPUlhudGcKLS0tIG5RUzlHd1V6M2duTHFUaXA1V2pa
            WFcrZk5ibFlGUnQycDQ5M09ZTTVYQWcKHZGNf810rXG/+/Jf20N1ZJG13YI5HVpS
            vvJQOy0f70GpykeoXSRRoBgfFhHeUG+pu7N+kDubsvvc/PIz4iKUfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T16:04:47Z"
    mac: ENC[AES256_GCM,data:mVHUdZy5AQMm/quYuDKxKhDY5y7w9m29347bjeRjNfSX6hsOkH3yFhVUZTqBszWez5uqSs6LIA+ZMKOy3EoTX5DWUoxht6soXLcKEY0Q/ZKn4xu01/oIs7nWJq/Fyp7EG2t0Rc5hcLhjUWGNeCE1rjMdA7p8kjKTI4aMwMlITHY=,iv:7EK96U7v8Swa8PMy4SYjB9y/oF3KI8odN0w5krTTO4I=,tag:oQsm+PDvVCRqt5XLdXBvEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
