apiVersion: viaduct.ai/v1
kind: ksops
metadata:
    name: ksops-config
    annotations:
        config.kubernetes.io/function: |
            exec:
                path: ksops
files:
    - ./secret/admin-password.yaml
    - ./secret/secret-key.yaml
    - ./secret/storage.yaml