apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.16.1
    releaseName: harbor
    namespace: harbor
    valuesFile: values.yaml