apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:SXk739PiZ2JKF6EUxwWY+muOOR2kX7N/ZNH9xP45gwitnIkJ0sxrdRMplW8SYBd7gBI48CV8KW7YAKOag9vRdVFFl7RP2YjSVtJpQlIEDd8gdAJ/NBmxSZ5BQzrhYYM7x131dHnGbNSnfm9tW1EmrQ==,iv:ej4aqSPIQZcnuut52DOScBSMDDaZWyD3VYLDBBRWUBE=,tag:6OQdBlR5Kn1rQW9XzJNFtQ==,type:str]
sops:
    age:
        - recipient: age1k7d7drqkwqawwfxhxzz6gd5ur7ns68xd5kpn69x8t6yvf9cp3pmsuukrgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVllvNE9LTWpGZmt5ZUZZ
            Z1k5YlpjVkVLVzJhQmlZbWMyNldzWFRrMEVNCkZZWEdmQ3BkQkNuMk4wQm1sVlJ2
            cTlOT3FNOHRJMkhNNVhnaTZJK0xjN0EKLS0tIG91NTY5TGpOOGlMcEQ5c2JyUVYy
            Z0V2bnkydGxMOVJUL0szR3IyNkozL1EKFQ3l7jjP/9fBM/yh0IJQUGjaY5EHR057
            J8yYMxprtU0Mv3a4BtsNuW/drVpLgJHiFg33+30d4hIsNkkdyYzXww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T15:43:36Z"
    mac: ENC[AES256_GCM,data:S7OJ/jcHjg68eE6sXkDXcT7sFroVcrMHYTAld1hmrnbiwz+asdwCoFkqcfBFQfweNq9TDpEwXcqiFTUDlEDxeqE2phmJMDBu5AGHVrgmGrWBeShc7CFmoTso5Dyzxp+CS/4ne42TWUB+3BkW4zYbrUhgVqkh5IH7iY/1fzYbiI4=,iv:XxVVtawfVyVLzVPr1Gqp3t5ZO4Tf3HiHigMyBwNelGY=,tag:XPAXHEriE71tC9j1F/b/XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
